// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.2
// source: clipboard.proto

package clipboard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ClipboardClient is the client API for Clipboard service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClipboardClient interface {
	ShareClipboard(ctx context.Context, in *ClipboardContent, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type clipboardClient struct {
	cc grpc.ClientConnInterface
}

func NewClipboardClient(cc grpc.ClientConnInterface) ClipboardClient {
	return &clipboardClient{cc}
}

func (c *clipboardClient) ShareClipboard(ctx context.Context, in *ClipboardContent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/clipboard_rpc.Clipboard/ShareClipboard", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClipboardServer is the server API for Clipboard service.
// All implementations must embed UnimplementedClipboardServer
// for forward compatibility
type ClipboardServer interface {
	ShareClipboard(context.Context, *ClipboardContent) (*emptypb.Empty, error)
	mustEmbedUnimplementedClipboardServer()
}

// UnimplementedClipboardServer must be embedded to have forward compatible implementations.
type UnimplementedClipboardServer struct {
}

func (UnimplementedClipboardServer) ShareClipboard(context.Context, *ClipboardContent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareClipboard not implemented")
}
func (UnimplementedClipboardServer) mustEmbedUnimplementedClipboardServer() {}

// UnsafeClipboardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClipboardServer will
// result in compilation errors.
type UnsafeClipboardServer interface {
	mustEmbedUnimplementedClipboardServer()
}

func RegisterClipboardServer(s grpc.ServiceRegistrar, srv ClipboardServer) {
	s.RegisterService(&Clipboard_ServiceDesc, srv)
}

func _Clipboard_ShareClipboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClipboardContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClipboardServer).ShareClipboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clipboard_rpc.Clipboard/ShareClipboard",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClipboardServer).ShareClipboard(ctx, req.(*ClipboardContent))
	}
	return interceptor(ctx, in, info, handler)
}

// Clipboard_ServiceDesc is the grpc.ServiceDesc for Clipboard service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Clipboard_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "clipboard_rpc.Clipboard",
	HandlerType: (*ClipboardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareClipboard",
			Handler:    _Clipboard_ShareClipboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "clipboard.proto",
}
